version: 2.1

commands:
  destroy-environment:
    description: Destroy EKS.    
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            eksctl delete cluster --name eksctl-demo --region=us-east-1

jobs:
  lint:
    docker:
      - image: circleci/node:16-bullseye-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: Lint
          command: |
            make lint
  
  build:
    docker:
      - image: docker:rc
    steps:
      - checkout      
      - run:
          name: Build react
          command: |
            DOCKER_PATH="thanhlam00290/udacity-project5"
            docker --version
            # docker build -t $DOCKER_PATH:${CIRCLE_WORKFLOW_ID:0:7} .
            # docker login -p ${DOCKER_PASSWORD} -u ${DOCKER_USERNAME}
            # docker push $DOCKER_PATH:${CIRCLE_WORKFLOW_ID:0:7}
  

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum install -y tar gzip
      - run:
          name: Ensure EKS exists
          command: |
            eksctl create cluster --name eksctl-demo --region=us-east-1      
      - destroy-environment      

  
  deploy-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y tar gzip curl unzip
      - run:
          name: Install kubectl
          command: |
            curl -LO https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - run:
          name: Deploy app
          command: |
            DOCKER_PATH="thanhlam00290/udacity-project5"
            sed 's+thanhlam00290/udacity-project5:0.1+$DOCKER_PATH:${CIRCLE_WORKFLOW_ID:0:7}+g' app-deployment.yml >> deploy.yml
            kubectl apply -f ./deploy.yml

  
workflows:
  default:
    jobs:
      - lint
      - build:
          requires: [lint]
      - deploy-app:
          requires: [build]
          filters:
            branches:
              only: [main]